name: Build and Push Docker Image

on:
  push:
    branches:
      - feature/ci-pipeline

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        docker build -t fabiosin/isen-python-fabio-sin:distroless-dev-${{ github.sha }} .

    - name: Push the Docker image
      run: |
        docker push fabiosin/isen-python-fabio-sin:distroless-dev-${{ github.sha }}
        
    - name: Vulnerability scanning with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: fabiosin/isen-python-fabio-sin:distroless-dev-${{ github.sha }}
        severity: HIGH,CRITICAL
        format: table
        exit-code: 0
        ignore-unfixed: true
