name: DAST Scan with ZAP

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run your application
        run: |
          docker build -t isen-python-app .
          docker run -d -p 8080:8080 --name isen-python-app isen-python-app
          sleep 15

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8080'
          cmd_options: "-config scanner.attackOnStart=false -config ajaxSpider.maxDuration=1"

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: report_json.json

      - name: Stop and remove docker container
        if: always()
        run: |
          docker stop isen-python-app || true
          docker rm isen-python-app || true
