name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: isen-python-service
        image: europe-west1-docker.pkg.dev/contract-central-c710c/cicd-class/isen-python:latest
